/**
 * DutyFreeAPI
 *
 * Bordo Bilişim Ticaret Ltd. ŞTİ 2021 ©
 *
 * The version of the OpenAPI document: v1.1.2
 * Contact: haci@bordo.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hvk.idf.data.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name name of current category
 * @param id Category ID
 * @param children children of current category
 */

data class CategoryTree (

    /* name of current category */
    @SerializedName("name")
    val name: String,

    /* Category ID */
    @SerializedName("id")
    val id: Int? = null,

    /* children of current category */
    @SerializedName("children")
    val children: String? = null

)

