/**
 * DutyFreeAPI
 *
 * Bordo Bilişim Ticaret Ltd. ŞTİ 2021 ©
 *
 * The version of the OpenAPI document: v1.1.2
 * Contact: haci@bordo.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hvk.idf.data.models


import com.google.gson.annotations.SerializedName
import java.net.URI
import java.time.OffsetDateTime

///**
// *
// *
// * @param name
// * @param url
// * @param slug Crawler slug
// * @param status
// * @param createdAt
// * @param finishedAt
// * @param startedAt
// */

data class Crawler(

    @SerializedName("name")
    val name: String,

    @SerializedName("url")
    val url: URI,

    /* Crawler slug */
    @SerializedName("slug")
    val slug: String,

    @SerializedName("status")
    val status: String? = null,

    @SerializedName("created_at")
    val createdAt: OffsetDateTime? = null,

    @SerializedName("finished_at")
    val finishedAt: OffsetDateTime? = null,

    @SerializedName("started_at")
    val startedAt: OffsetDateTime? = null

)

