/**
 * DutyFreeAPI
 *
 * Bordo Bilişim Ticaret Ltd. ŞTİ 2021 ©
 *
 * The version of the OpenAPI document: v1.1.2
 * Contact: haci@bordo.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hvk.idf.data.models


import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param crawlerSlug slug of the dutyfree crawler to run
 * @param cronExpression cron expression to run the crawler
 */

data class SchedulerCron(

    /* slug of the dutyfree crawler to run */
    @SerializedName( "crawler_slug")
    val crawlerSlug: String,

    /* cron expression to run the crawler */
    @SerializedName( "cron_expression")
    val cronExpression: String

)

