/**
 * DutyFreeAPI
 *
 * Bordo Bilişim Ticaret Ltd. ŞTİ 2021 ©
 *
 * The version of the OpenAPI document: v1.1.2
 * Contact: haci@bordo.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.hvk.idf.data.models


import com.google.gson.annotations.SerializedName
import java.time.OffsetDateTime

/**
 *
 *
 * @param crawlerSlug slug of the dutyfree crawler to run
 * @param runDate date to run the crawler
 */

data class SchedulerDate(

    /* slug of the dutyfree crawler to run */
    @SerializedName("crawler_slug")
    val crawlerSlug: String,

    /* date to run the crawler */
    @SerializedName("run_date")
    val runDate: OffsetDateTime

)

